name: Build & Deploy for Testing

on:
  push:
    branches:
      - master

  workflow_dispatch:
  
jobs:
  test-build:
    name: Build Hybrid
    runs-on: ubuntu-latest
    steps:

#     Checkout everything
      - name: Checkout threatrix master repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Checkout repos core 
        id: core
        continue-on-error: true
        uses: actions/checkout@v2
        with:
          repository: threatrix/core
          token: '${{ secrets.TOKEN }}'
          path: core
          ref: ${{ github.head_ref }}
#
